export const GOOGLE_SHEETS_ID = "1qS7yrrPvKIIJ_OvuYEyw1dNYq2nWCLU2k-IAIc4hTyU";
export const GOOGLE_SHEETS_URL = `https://docs.google.com/spreadsheets/d/${GOOGLE_SHEETS_ID}/export?format=csv`;

export const PREFERRED_LANGS = [['de-DE', 'de_DE'], ['en-US', 'en_US']];

export const ELIGIBLE_ROW_SYMBOL = 'y';

export const ALLLANGUAGES = [
    { label: 'English (United States)', value: ['en-US', 'en_US'] },
    { label: 'English (United Kingdom)', value: ['en-GB', 'en_GB'] },
    { label: 'French (France)', value: ['fr-FR', 'fr_FR'] },
    { label: 'Spanish (Spain)', value: ['es-ES', 'es_ES'] },
    { label: 'German (Germany)', value: ['de-DE', 'de_DE'] },
    { label: 'Chinese (China)', value: ['zh-CN', 'zh_CN'] },
    { label: 'Chinese (Hong Kong)', value: ['zh-HK', 'zh_HK'] },
    { label: 'Chinese (Taiwan)', value: ['zh-TW', 'zh_TW'] },
    { label: 'Arabic (Saudi Arabia)', value: ['ar-SA', 'ar_SA'] },
    { label: 'Hindi (India)', value: ['hi-IN', 'hi_IN'] },
    { label: 'Russian (Russia)', value: ['ru-RU', 'ru_RU'] },
    { label: 'Japanese (Japan)', value: ['ja-JP', 'ja_JP'] },
    { label: 'Korean (Korea)', value: ['ko-KR', 'ko_KR'] },
    { label: 'Italian (Italy)', value: ['it-IT', 'it_IT'] },
    { label: 'Portuguese (Brazil)', value: ['pt-BR', 'pt_BR'] },
    { label: 'Portuguese (Portugal)', value: ['pt-PT', 'pt_PT'] },
    { label: 'Dutch (Netherlands)', value: ['nl-NL', 'nl_NL'] },
    { label: 'Swedish (Sweden)', value: ['sv-SE', 'sv_SE'] },
    { label: 'Turkish (Turkey)', value: ['tr-TR', 'tr_TR'] },
    { label: 'Spanish (United States)', value: ['es-US', 'es_US'] },
    { label: 'Indonesian (Indonesia)', value: ['id-ID', 'id_ID', 'in-ID', 'in_ID'] },
    { label: 'Polish (Poland)', value: ['pl-PL', 'pl_PL'] },
    { label: 'Assamese (India)', value: ['as-IN', 'as_IN'] },
    { label: 'Bulgarian (Bulgaria)', value: ['bg-BG', 'bg_BG'] },
    { label: 'Bengali (Bangladesh)', value: ['bn-BD', 'bn_BD'] },
    { label: 'Bengali (India)', value: ['bn-IN', 'bn_IN'] },
    { label: 'Bodo (India)', value: ['brx-IN', 'brx_IN'] },
    { label: 'Bosnian (Cyrillic, Bosnia and Herzegovina)', value: ['bs-BA-#Cyrl', 'bs_BA_#Cyrl'] },
    { label: 'Bosnian (Latin, Bosnia and Herzegovina)', value: ['bs-BA-#Latn', 'bs_BA_#Latn'] },
    { label: 'Catalan (Spain)', value: ['ca-ES', 'ca_ES'] },
    { label: 'Czech (Czech Republic)', value: ['cs-CZ', 'cs_CZ'] },
    { label: 'Welsh (United Kingdom)', value: ['cy-GB', 'cy_GB'] },
    { label: 'Danish (Denmark)', value: ['da-DK', 'da_DK'] },
    { label: 'Dogri (India)', value: ['doi-IN', 'doi_IN'] },
    { label: 'Greek (Greece)', value: ['el-GR', 'el_GR'] },
    { label: 'English (Australia)', value: ['en-AU', 'en_AU'] },
    { label: 'English (India)', value: ['en-IN', 'en_IN'] },
    { label: 'English (Nigeria)', value: ['en-NG', 'en_NG'] },
    { label: 'Estonian (Estonia)', value: ['et-EE', 'et_EE'] },
    { label: 'Finnish (Finland)', value: ['fi-FI', 'fi_FI'] },
    { label: 'Filipino (Philippines)', value: ['fil-PH', 'fil_PH'] },
    { label: 'French (Canada)', value: ['fr-CA', 'fr_CA'] },
    { label: 'Gujarati (India)', value: ['gu-IN', 'gu_IN'] },
    { label: 'Hebrew (Israel)', value: ['iw-IL', 'iw_IL', 'he-IL', 'he_IL'] },
    { label: 'Hindi (India, Latin script)', value: ['hi-IN-#Latn', 'hi_IN_#Latn'] },
    { label: 'Croatian (Croatia)', value: ['hr-HR', 'hr_HR'] },
    { label: 'Hungarian (Hungary)', value: ['hu-HU', 'hu_HU'] },
    { label: 'Icelandic (Iceland)', value: ['is-IS', 'is_IS'] },
    { label: 'Javanese (Indonesia)', value: ['jv-ID', 'jv_ID'] },
    { label: 'Khmer (Cambodia)', value: ['km-KM', 'km_KM', 'km-KH', 'km_KH',] },
    { label: 'Kannada (India)', value: ['kn-IN', 'kn_IN'] },
    { label: 'Konkani (India)', value: ['kok-IN', 'kok_IN'] },
    { label: 'Kashmiri (India, Arabic script)', value: ['ks-IN-#Arab', 'ks_IN_#Arab'] },
    { label: 'Kashmiri (India, Devanagari script)', value: ['ks-IN-#Deva', 'ks_IN_#Deva'] },
    { label: 'Lithuanian (Lithuania)', value: ['lt-LT', 'lt_LT'] },
    { label: 'Latvian (Latvia)', value: ['lv-LV', 'lv_LV'] },
    { label: 'Maithili (India)', value: ['mai-IN', 'mai_IN'] },
    { label: 'Malayalam (India)', value: ['ml-IN', 'ml_IN'] },
    { label: 'Manipuri (India, Bengali script)', value: ['mni-IN-#Beng', 'mni_IN_#Beng'] },
    { label: 'Marathi (India)', value: ['mr-IN', 'mr_IN'] },
    { label: 'Malay (Malaysia)', value: ['ms-MY', 'ms_MY'] },
    { label: 'Norwegian Bokmål (Norway)', value: ['nb-NO', 'nb_NO'] },
    { label: 'Nepali (Nepal)', value: ['ne-NP', 'ne_NP'] },
    { label: 'Dutch (Belgium)', value: ['nl-BE', 'nl_BE'] },
    { label: 'Odia (India)', value: ['or-IN', 'or_IN'] },
    { label: 'Punjabi (India, Gurmukhi script)', value: ['pa-IN-#Guru', 'pa_IN_#Guru'] },
    { label: 'Romanian (Romania)', value: ['ro-RO', 'ro_RO'] },
    { label: 'Sanskrit (India)', value: ['sa-IN', 'sa_IN'] },
    { label: 'Santali (India, Ol Chiki script)', value: ['sat-IN-#Olck', 'sat_IN_#Olck'] },
    { label: 'Sinhala (Sri Lanka)', value: ['si-LK', 'si_LK'] },
    { label: 'Slovak (Slovakia)', value: ['sk-SK', 'sk_SK'] },
    { label: 'Slovenian (Slovenia)', value: ['sl-SI', 'sl_SI'] },
    { label: 'Albanian (Albania)', value: ['sq-AL', 'sq_AL'] },
    { label: 'Serbian (Serbia, Cyrillic script)', value: ['sr-RS-#Cyrl', 'sr_RS_#Cyrl'] },
    { label: 'Serbian (Serbia, Latin script)', value: ['sr-RS-#Latn', 'sr_RS_#Latn'] },
    { label: 'Sundanese (Indonesia, Latin script)', value: ['su-ID-#Latn', 'su_ID_#Latn'] },
    { label: 'Sindhi (India, Devanagari script)', value: ['sd-IN-#Deva', 'sd_IN_#Deva'] },
    { label: 'Swahili (Kenya)', value: ['sw-KE', 'sw_KE'] },
    { label: 'Tamil (India)', value: ['ta-IN', 'ta_IN'] },
    { label: 'Telugu (India)', value: ['te-IN', 'te_IN'] },
    { label: 'Thai (Thailand)', value: ['th-TH', 'th_TH'] },
    { label: 'Ukrainian (Ukraine)', value: ['uk-UA', 'uk_UA'] },
    { label: 'Urdu (India)', value: ['ur-IN', 'ur_IN'] },
    { label: 'Urdu (Pakistan)', value: ['ur-PK', 'ur_PK'] },
    { label: 'Vietnamese (Vietnam)', value: ['vi-VN', 'vi_VN'] },
    { label: 'Cantonese (Hong Kong, Traditional script)', value: ['yue-HK-#Hant', 'yue_HK_#Hant'] },
    { label: 'Chinese (China, Simplified script)', value: ['zh-CN-#Hans', 'zh_CN_#Hans'] },
    { label: 'Chinese (Hong Kong, Simplified script)', value: ['zh-HK-#Hans', 'zh_HK_#Hans'] },
    { label: 'Chinese (Macau, Simplified script)', value: ['zh-MO-#Hans', 'zh_MO_#Hans'] },
    { label: 'Chinese (Singapore, Simplified script)', value: ['zh-SG-#Hans', 'zh_SG_#Hans'] },
    { label: 'Chinese (Hong Kong, Traditional script)', value: ['zh-HK_#Hant', 'zh_HK_#Hant'] },
    { label: 'Chinese (Macau, Traditional script)', value: ['zh-MO_#Hant', 'zh_MO_#Hant'] },
    { label: 'Chinese (Taiwan, Traditional script)', value: ['zh-TW_#Hant', 'zh_TW_#Hant'] },
  ];